package com.teacher.vocabcheck.engine

/**
 * 规则变形覆盖不到的特殊形式。value 为逗号分隔，便于手工增补。
 */
object Irregular {

    /** 基础形式 -> 其他形式（三单/过去式/过去分词/现在分词等） */
    private val VERBS_CSV = mapOf(
        "be" to "am,is,are,was,were,been,being",
        "begin" to "begins,began,beginning",
        "bend" to "bends,bent,bent",
        "bet" to "bets,bet,betting,betted",
        "bind" to "binds,bound,binding",
        "bite" to "bites/bit/bitten/biting",
        "bleed" to "bleeds,bled,bleeding",
        "blow" to "blows,blew,blown,blowing",
        "break" to "breaks,broke,broken,breaking",
        "breed" to "breeds,bred,breeding",
        "bring" to "brings,brought,bringing",
        "broadcast" to "broadcasts,broadcast,broadcasting",
        "build" to "builds,built,building",
        "burn" to "burns,burned,burnt,burning",
        "buy" to "buys,bought,buying",
        "can" to "could",
        "catch" to "catches,caught,catching",
        "choose" to "chooses,chose,chosen,choosing",
        "cling" to "clings,clung,clinging",
        "come" to "comes,came,coming",
        "cost" to "costs,cost,costing",
        "creep" to "creeps,crept,creeping",
        "cut" to "cuts,cutting",
        "deal" to "deals,dealt,dealing",
        "dig" to "digs,dug,digging",
        "do" to "does,doing,did,done,dost,doth",
        "draw" to "draws,drew,drawn,drawing",
        "dream" to "dreams,dreamed,dreamt,dreaming",
        "drink" to "drinks,drunk,drank,drinking",
        "drive" to "drives,drove,driven,driving",
        "eat" to "eats,ate,eaten,eating",
        "fall" to "falls,fell,fallen,falling",
        "feed" to "feeds,fed,feeding",
        "feel" to "feels,felt,feeling",
        "fight" to "fights,fought,fighting",
        "find" to "finds,found,finding",
        "flee" to "flees,fled,fleeing",
        "fling" to "flings,flung,flinging",
        "forget" to "forgets,forgot,forgotten,forgetting",
        "forgive" to "forgives,forgave,forgiven,forgiving",
        "freeze" to "freezes,froze,frozen,freezing",
        "get" to "gets,got,gotten,getting",
        "give" to "gives,gave,given,giving",
        "go" to "goes,went,gone,going",
        "grow" to "grows,grew,grown,growing",
        "hang" to "hangs,hanged,hung,hanging",
        "have" to "has,having,had,hast",
        "hear" to "hears,heard,hearing",
        "hide" to "hides,hid,hidden,hiding",
        "hit" to "hits,hitting",
        "hold" to "holds,held,holding",
        "hurt" to "hurts,hurting",
        "keep" to "keeps,kept,keeping",
        "kneel" to "kneels,kneeled,knelt,kneeling",
        "know" to "knows,knew,known,knowing",
        "lay" to "lays,lying,lied,laying",
        "lead" to "leads,led,leading",
        "learn" to "learns,learned,learnt,learning",
        "leave" to "leaves,left,leaving",
        "lend" to "lends,lent,lending",
        "let" to "lets,letting",
        "lie" to "lies,lied,lying,lain",
        "light" to "lights,lighted,lit,lighting",
        "lose" to "loses,lost,losing",
        "make" to "makes,made,making",
        "mean" to "means,meant,meaning",
        "meet" to "meets,met,meeting",
        "may" to "might",
        "pay" to "pays,paid,paying",
        "put" to "puts,putting",
        "read" to "reads,reading",
        "ride" to "rides,rode,ridden,riding",
        "ring" to "rings,rang,rung,ringing",
        "rise" to "rises,rose,risen,rising",
        "run" to "runs,ran,running",
        "say" to "says,said,saying",
        "see" to "sees,saw,seen,seeing",
        "seek" to "seeks,sought,seeking",
        "sell" to "sells,sold,selling",
        "send" to "sends,sent,sending",
        "set" to "sets,setting",
        "shine" to "shines,shone,shining",
        "shoot" to "shoots,shot,shooting",
        "show" to "shows,showed,shown,showing",
        "shut" to "shuts,shutting",
        "sing" to "sings,sang,sung,singing",
        "sink" to "sinks,sank,sunk,sinking",
        "sit" to "sits,sat,sitting",
        "sleep" to "sleeps,slept,sleeping",
        "smell" to "smells,smelled,smelt,smelling",
        "speak" to "speaks,spoke,spoken,speaking",
        "spend" to "spends,spent,spending",
        "spell" to "spells,spelled,spelt,spelling",
        "spread" to "spreads,spreading",
        "stand" to "stands,stood,standing",
        "steal" to "steals,stole,stolen,stealing",
        "stick" to "sticks,stuck,sticking",
        "sting" to "stings,stung,stinging",
        "strike" to "strikes,struck,stricken,striking",
        "swear" to "swears,swore,sworn,swearing",
        "sweep" to "sweeps,swept,sweeping",
        "swim" to "swims,swam,swum,swimming",
        "swing" to "swings,swung,swinging",
        "take" to "takes,took,taken,taking",
        "teach" to "teaches,taught,teaching",
        "tear" to "tears,tore,torn,tearing",
        "tell" to "tells,told,telling",
        "think" to "thinks,thought,thinking",
        "throw" to "throws,threw,thrown,throwing",
        "understand" to "understands,understood,understanding",
        "wake" to "wakes,woke,woken,waking,waked",
        "wear" to "wears,wore,worn,wearing",
        "weep" to "weeps,wept,weeping",
        "will" to "would",
        "win" to "wins,won,winning",
        "wind" to "winds,wound,winding",
        "write" to "writes,wrote,written,writing",
        "shall" to "should",
        "must" to "musts"
    )

    private val NOUNS_CSV = mapOf(
        "child" to "children,childes",
        "man" to "men",
        "woman" to "women",
        "foot" to "feet",
        "tooth" to "teeth",
        "goose" to "geese",
        "mouse" to "mice",
        "louse" to "lice",
        "ox" to "oxen",
        "person" to "people,persons",
        "criterion" to "criteria",
        "phenomenon" to "phenomena",
        "datum" to "data",
        "medium" to "media,mediums",
        "analysis" to "analyses",
        "basis" to "bases",
        "crisis" to "crises",
        "thesis" to "theses",
        "index" to "indices,indexes",
        "matrix" to "matrices,matrixes",
        "appendix" to "appendices,appendixes",
        "syllabus" to "syllabi,syllabuses",
        "cactus" to "cacti,cactuses",
        "focus" to "foci,focuses",
        "thief" to "thieves",
        "sheep" to "sheep",
        "deer" to "deer",
        "fish" to "fishes",
        "series" to "series",
        "species" to "species",
        "aircraft" to "aircraft"
    )

    private val ADJECTIVES_CSV = mapOf(
        "good" to "better,best",
        "well" to "better,best",
        "bad" to "worse,worst",
        "ill" to "worse,worst",
        "far" to "farther,further,farthest,furthest",
        "little" to "less,least",
        "many" to "more,most",
        "much" to "more,most",
        "old" to "older,oldest,elder,eldest"
    )

    /** 以 -l/-r 结尾且需双写的多音节常用词 */
    val MULTI_SYLLABLE_DOUBLE = setOf(
        "travel", "cancel", "counsel", "total", "label", "model", "fuel",
        "visit", "profit", "benefit", "target", "open", "close"
    )

    val verbs: Map<String, Set<String>> by lazy { VERBS_CSV.parse() }
    val nouns: Map<String, Set<String>> by lazy { NOUNS_CSV.parse() }
    val adjectives: Map<String, Set<String>> by lazy { ADJECTIVES_CSV.parse() }

    val defective: Set<String> = setOf("cannot", "might", "must", "shall", "should", "will", "would", "could")

    private fun Map<String, String>.parse(): Map<String, Set<String>> =
        entries.associate { (base, csv) -> base to csv.split(',').map { it.trim() }.filter { it.isNotEmpty() }.toSet() }
}
